//
// Created by sERGI vIVES on 21/5/2020.
//

#ifndef ORDENACIOCERCACOST_ERRORCODES_H
#define ORDENACIOCERCACOST_ERRORCODES_H

// Errorcodes de les EDs
#define EXIT 0
#define ERROR_CREATE 1
#define ERROR_DESTROY 2
#define ERROR_NONEXISTENT_DE 3
#define ERROR_EMPTY_DE 4
#define ERROR_FULL_DE 5
#define ERROR_BAD_PARAMETERS 6

#endif //ORDENACIOCERCACOST_ERRORCODES_H
